sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: zDAcp98XFm9oqwSGohT04aM1naiokssTNQQfaICjccNfvwUVxDg0mWschLr1VM5R+juX3hG4w3oT0kGK7QtT+kgcEDUFWTe09zAPNqITec7rfZMJ85vfQSilkDjF+vnZSa8cGqG5hsP1cTlH7RQ2cw1E8uMEefEnYvdbqYacQ7latoy5dpQxd2665GOt35oXXDU7LxNLb8k8QRZETVMrRwnIJbSlg8pIjoiO4bI5F6TDvbtPyM1p3cgDvW+Vk8YhnX4YEv62eQ1p7Q7PUlCZNTe6Gq6bPn5Y+i/fISwWZkFt2RQWh5/wWd27uSDzhJ1tYi9PKGDPDk8VGSX41BhUTsis6t3hzZlz1KJGeuzBbMNkkqqjMNM+KeAYi7SDfjJK4PRgSjBpthhmstBHDWj9qyRKb/94dvpxprnvB0pJ2dfiLYaUs7OJCNQNfc8D74AMWHCZCFkls2b+RENRFN2wEO5PT8xRewFqqcQyStSEZMehpMsnG3A6Ex4TlAXGqzNH/6+IudNbtWZRxShGPYNlQCcLfNZUqpHi7WvFhqKRAatqdTYsWlDCndq6zeGsHDyKiCmp+iZU12Lc+SRc7fEek+7ZkPdfb6zSMnWsj9TUCitarxNNIvWkFthmjXT1J7zmZdusUqqR4DUfi+STc5ia8kih6CNJJcmJlIa4OUMtZwg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Mr.-Honey-s-Banking-Dictionary--German-English-_3298
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy